Gordeenko/Task4 - in work
MikitaTsiarentsyeu/Md-PT1-46-22 pull request #64
Opened 2022-02-08 15:55 UTC by IrinaGordeenko

Task4 - in work

2022-02-09 06:16 UTC, MikitaTsiarentsyeu requested changes
OK, I will wait for a complete version)

2022-02-15 20:44 UTC, IrinaGordeenko commented
> OK, I will wait for a complete version)

Add new file - Task4_new.py
Code Update for Task4, but I have a question.
How to create a list from the terminal? How to do it from parallel (print) ?

2022-02-16 05:33 UTC, MikitaTsiarentsyeu approved these changes
This could be better, the score is 7.

As for your question - lets discuss it in class, it will be more clear.

2022-02-16 05:33 UTC, MikitaTsiarentsyeu commented on Tasks/Gordeenko/Task4/Task4_new.py
> +    f.writelines(l)
l is the last line of the file, not exactly correct

2022-02-16 05:33 UTC, merged